apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-konnect
  labels:
    app: mcp-konnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-konnect
  template:
    metadata:
      labels:
        app: mcp-konnect
    spec:
      imagePullSecrets:
      - name: dockerhub-user-secret
      containers:
      - name: mcp-konnect
        image: kong/sales-engineering:mcp-konnect-${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: KONNECT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: konnect-api-access-token
              key: token
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-konnect
spec:
  selector:
    app: mcp-konnect
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP